kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wwwroot-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: worker-nfs-150
