apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: wwwroot
          mountPath: /usr/share/nginx/html
        - name: defaultconf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
        - name: wwwroot
          persistentVolumeClaim:
            claimName: wwwroot-pvc
        - name: defaultconf
          configMap:
            name: defaultconf
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: nginx-test
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32500
